name: Azure Deployment

on:
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in with Azure
        uses: azure/login@v1
        with:
          creds: "${{ secrets.AZURE_CREDENTIALS }}"

      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          azcliversion: latest
          inlineScript: |
            az account show

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ajaxclusteringlok.azurecr.io
          username: ajaxclusteringlok.azurecr.io
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push backend Docker image
        working-directory: backend
        run: |
          docker build . -t ajaxclusteringlok.azurecr.io/backend-b15-lok:${{ github.sha }}
          docker push ajaxclusteringlok.azurecr.io/backend-b15-lok:${{ github.sha }}

      - name: Build and push frontend Docker image
        working-directory: frontend
        run: |
          docker build . -t ajaxclusteringlok.azurecr.io/frontend-b15-lok:${{ github.sha }}
          docker push ajaxclusteringlok.azurecr.io/frontend-b15-lok:${{ github.sha }}

      - name: Deploy to Azure Web App - Backend
        uses: azure/webapps-deploy@v2
        with:
          app-name: backend-app-b15-lok
          images: ajaxclusteringlok.azurecr.io/backend-b15-lok:${{ github.sha }}

      - name: Deploy to Azure Web App - Frontend
        uses: azure/webapps-deploy@v2
        with:
          app-name: frontend-app-b15-lok
          images: ajaxclusteringlok.azurecr.io/frontend-b15-lok:${{ github.sha }}
