name: Azure Deployment

on:
  push:
    branches:
      - master 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Login to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ajaxclusterappacr.azurecr.io
        username: ajaxclusterappacr
        password: ${{ secrets.ACR_PASSWORD }}
        
    - name: Build and push backend Docker image
      working-directory: backend
      run: |
        docker build . -t ajaxclusterappacr.azurecr.io/backend:${{ github.sha }}
        docker push ajaxclusterappacr.azurecr.io/backend:${{ github.sha }}
        
    - name: Build and push frontend Docker image
      working-directory: frontend
      run: |
        docker build . -t ajaxclusterappacr.azurecr.io/frontend:${{ github.sha }}
        docker push ajaxclusterappacr.azurecr.io/frontend:${{ github.sha }}
        
    - name: Deploy to Azure Web App - Backend
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'backend-app'  # Replace with your Azure Web App name
        images: 'ajaxclusterappacr.azurecr.io/backend:${{ github.sha }}'
        
    - name: Deploy to Azure Web App - Frontend
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'frontend-app'  # Replace with your Azure Web App name
        images: 'ajaxclusterappacr.azurecr.io/frontend:${{ github.sha }}'
        
